### ISSUE TITLE
Memory loss

### ISSUE THREAD

**Issue by pashajanx** [Jako/PDFResource#21] opened 2017-12-02 17:19 UTC
When saving a resource, an error occurs.

`Allowed memory size of 268435456 bytes exhausted (tried to allocate 130968 bytes) in "../core/xpdo/om/xpdoobject.class.php on line 1737"`

modx 2.6.0
php 5.6.24

p.s Disable all plugins except PDFResource, Error not lost.

**Comment by Jako** [comment] 2017-12-03 11:04
Duplicate of #18

**Closed by Jako** 2017-12-03 11:04 UTC
