### ISSUE TITLE
Fatal error with PHP 7.0.8

### ISSUE THREAD

**Issue by superspace** [Jako/PDFResource#10] opened 2016-08-08 15:46 UTC
Running on PHP 7.0.8 creating a PDF ends with the following error:

PHP Fatal error:  'break' not in the 'loop' or 'switch' context in …/core/components/pdfresource/vendor/mpdf/mpdf/classes/svg.php on line 2710

This Batch does fix it:

2710 -						if (!$last_gradid) break;
2710 +						if (!$last_gradid) return;

**Comment by Jako** [comment] 2016-08-08 16:51
Could you look in the mpdf repository, if the issue is filed there, too?

Von meinem iPhone gesendet

**Comment by Jako** [comment] 2016-08-15 06:39
This was already fixed in mPDF https://github.com/mpdf/mpdf/commit/002bb8ae97f81299ac79e472a86c051993e43444

Updated the vendor package in the 1.5.3 release.

**Closed by Jako** 2016-08-15 06:39 UTC
